// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using Eco.Gameplay.Blocks;
    using Eco.Shared.Localization;

    public partial class RampsFormGroup : FormGroup
    {
        public override string Name => "Ramps";
        public override LocString DisplayName => Localizer.DoStr("Ramps");
        public override LocString DisplayDescription => Localizer.DoStr("Ramps");
        public override int SortOrder => 7;
    }
}
