// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using Eco.Gameplay.Blocks;
    using Eco.Shared.Localization;
    using Eco.World.Blocks;
    public partial class BraceFormType : FormType
    {
        public override string Name => "Brace";
        public override LocString DisplayName => Localizer.DoStr("Brace");
        public override LocString DisplayDescription => Localizer.DoStr("Brace");
        public override Type GroupType => typeof(SupportsFormGroup);
        public override int SortOrder => 25;
        public override int MinTier => 1;
    }
}
