// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using Eco.Gameplay.Blocks;
    using Eco.Shared.Localization;
    using Eco.World.Blocks;
    public partial class SideBraceFormType : FormType
    {
        public override string Name => "SideBrace";
        public override LocString DisplayName => Localizer.DoStr("Side Brace");
        public override LocString DisplayDescription => Localizer.DoStr("Side Brace");
        public override Type GroupType => typeof(SupportsFormGroup);
        public override int SortOrder => 27;
        public override int MinTier => 1;
    }
}
